version: '3.7'
services:
    display:
        build: ./display/
        container_name: display
        restart: unless-stopped
        privileged: true
        environment: 
            URL: "https://coppertop.ca"
            DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
        volumes:
            - /run/dbus/system_bus_socket:/host/run/dbus/system_bus_socket
        links:
            - wifi-connect

    wifi-connect:
        build: ./wifi-connect/
        container_name: wifi-connect
        restart: unless-stopped
        network_mode: "host"
        cap_add:
            - NET_ADMIN
        environment:
            DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/var/run/dbus/system_bus_socket"
        volumes:
            - /run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
        privileged: true