#cloud-config
# vim: syntax=yaml
#
hostname: rpi-hydrogen
manage_etc_hosts: true

users:
  - name: thomasga
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,docker,adm,dialout,audio,plugdev,netdev,video
    lock_passwd: true
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDzIqds6oy9JMdDlMMo+sn4BKoAFl5d3YFVAm+gzgRx6geLgekCT0xeFJgvXjKDJ367Da/OJm5TKkO3n4CYUnQ7djFrsAAM+SO+PrmFxiiuVFXlcfjukUwrImqDOR6uIwuUbXsowCCThPnw/AVivfRZ2FmGWIeIKmefXoU3zRj2Q8LLyw9JXRMseUKtQlhis0lhas50mqNPUetji5Ve1TA3AFXijiCEscc8YDz9o0Jn4VHWcdtB9d0Vcni8vVxaSg/Mm/qWk7v6dDQOqvoI4N11Ua0EcpCndB7e6QXCJpZkwOvALx8/o/ko/JqstOT+xn3ok2FK6BbA2xsTWx73Rk6iCfMmsOLsR4lssnrsGWhCxGLie7Wp3uCcfz0sNd8GRW0o9rTE6S5lGA7K+71qYZRUl5rZV/7gxJ+bvdcIhD5aRUsnbcC79PvpxSEL4swGkccJQfB8NolDYIWO7uOxY69wc5giupORy53yVubKJcn01HzFXw3J1zSojjnqZIjOlG7kmnMVXa4uLQeyqfeTamXA/oo8a6kUXOlgX0hSft3mwrjwBsGl87R86OASwOh4IlX0ZQ+K5Hgay5WgUAwr4JAbAUi/PLfK4Egg/5V9VQ49r39AZ4usLY2n1X5Nk2lAe9QZHASEaFluwlr29vn/HH6Z+GrPkFJM+Cnsyzkp6lQSDQ== thomasg@Geoffreys-iMac.local
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4DwiCYw4sz5MZ6a2HMagPxgXvLj0z2NdK8CVW+7Vbu1u3we7d4d/K+TfDp3D6fKUR74hwkWDcEhWK2bCELQWFWgMkuGGcHNlsdHbCaSVzTZGpEeqvmMirC2QILsdOCMWYLOOigMh5ux+IF1AzbptYKoFhZPOQNBReuAM2nuThYIdTR9eBMsvIehHe1HRB9SFJ47qCxM7AIfd8D1O8zZuYtaylaBBCanBF0TXumJvDn/N5s0Bp38rfVPM+FtrpyLT+XscyIlIf/HNRj/BDOtkIxq59UlcI6inH+0Br/e6B9c/3VEArH925oUOjWVZhPJ8zV/yDT20INQKK9tJA7MQF thomasga@Geoffreys-MacBook-Air.local

package_upgrade: false

# # Set the locale of the system
locale: "en_US.UTF-8"

# # Set the timezone
# # Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: "America/Edmonton"

# # WiFi connect to HotSpot
# To make wifi work with RPi3 and RPi0
# you also have to set "enable_uart=0" in config.txt
write_files:
  - content: |
      # This file describes the network interfaces available on your system
      # and how to activate them. For more information, see interfaces(5).

      allow-hotplug wlan0
      iface wlan0 inet dhcp
          wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
      iface default inet dhcp
    path: /etc/network/interfaces.d/wlan0
  - content: |
      # This file describes the network interfaces available on your system
      # and how to activate them. For more information, see interfaces(5).

      allow-hotplug eth0
      iface eth0 inet dhcp
    path: /etc/network/interfaces.d/eth0
  - content: |
      country=CA
      ctrl_interface=DIR=/run/wpa_supplicant GROUP=netdev
      update_config=1
    path: /etc/wpa_supplicant/wpa_supplicant.conf

# These commands will be run once on first boot only
runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'

  - 'ifdown eth0; ifup eth0'

  - 'sleep 10'

  - 'git clone "https://github.com/geoff-coppertop/3d-printer" ./'

  - './hypriot/setup.sh'

power_state:
  delay: now
  mode: reboot
  message: Bye Bye
  timeout: 30
  condition: True