accessControl:
    enabled: false
api:
    key: A48F422F023F4961A01FA29D6C7BCD93
plugins:
    announcements:
        _config_version: 1
        channels:
            _blog:
                read_until: 1589460900
            _important:
                read_until: 1521111600
            _octopi:
                read_until: 1573722900
            _plugins:
                read_until: 1591419600
            _releases:
                read_until: 1583322300
    discovery:
        upnpUuid: cd15611b-5140-46a6-b920-9879af6618c1
    errortracking:
        unique_id: 839971c2-2fd0-452d-beea-d431a84da4a5
    softwareupdate:
        _config_version: 7
    tracking:
        enabled: false
        unique_id: b8f8025b-8e0b-4b8f-aa5b-5dd57df90992
printerProfiles:
    default: _default
server:
    firstRun: false
    onlineCheck:
        enabled: true
    pluginBlacklist:
        enabled: true
    secretKey: BrHwYh5Xd3g3jFEOA56hXjYAhihnKdfA
    seenWizards:
        corewizard: 3
        tracking: null
temperature:
    profiles:
    -   bed: 100
        chamber: null
        extruder: 210
        name: ABS
    -   bed: 60
        chamber: null
        extruder: 180
        name: PLA
